name: Training theme
type: theme
base theme: classy
description: A flexible theme with a responsive, mobile-first layout.
package: Custom
core: 8.x
core_version_requirement: ^8 || ^9
libraries:
  - training/global
