# Schema for the configuration files of the Training theme theme.
training.settings:
  type: theme_settings
  label: 'Training theme settings'
  mapping:
    font_size:
      type: integer
      label: Font size
